import Head from 'next/head'
import type { NextPage } from 'next'
import Scroll from '@/components/Scroll'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Scroll />
      </main>
    </>
  )
}

export default Home
